/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Language = IDL.Text;
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'offline' : IDL.Null,
});
export const ShortProfile = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'fullName' : IDL.Text,
  'nativeLanguages' : IDL.Vec(Language),
  'targetLanguages' : IDL.Vec(Language),
  'currentStatus' : Status,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'fullName' : IDL.Text,
  'sentMatchRequests' : IDL.Vec(IDL.Principal),
  'matches' : IDL.Vec(IDL.Principal),
  'nativeLanguages' : IDL.Vec(Language),
  'targetLanguages' : IDL.Vec(Language),
  'lastActive' : IDL.Int,
  'currentStatus' : Status,
  'lastMessageCheck' : IDL.Int,
  'receivedMatchRequests' : IDL.Vec(IDL.Principal),
});
export const MatchAction = IDL.Record({
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUserProfile' : IDL.Func([ShortProfile], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentActiveParticipants' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Status))],
      ['query'],
    ),
  'getCurrentUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getMatches' : IDL.Func([], [IDL.Vec(MatchAction)], []),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Language = IDL.Text;
  const Status = IDL.Variant({ 'active' : IDL.Null, 'offline' : IDL.Null });
  const ShortProfile = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'fullName' : IDL.Text,
    'nativeLanguages' : IDL.Vec(Language),
    'targetLanguages' : IDL.Vec(Language),
    'currentStatus' : Status,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'fullName' : IDL.Text,
    'sentMatchRequests' : IDL.Vec(IDL.Principal),
    'matches' : IDL.Vec(IDL.Principal),
    'nativeLanguages' : IDL.Vec(Language),
    'targetLanguages' : IDL.Vec(Language),
    'lastActive' : IDL.Int,
    'currentStatus' : Status,
    'lastMessageCheck' : IDL.Int,
    'receivedMatchRequests' : IDL.Vec(IDL.Principal),
  });
  const MatchAction = IDL.Record({
    'user' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUserProfile' : IDL.Func([ShortProfile], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentActiveParticipants' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Status))],
        ['query'],
      ),
    'getCurrentUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getMatches' : IDL.Func([], [IDL.Vec(MatchAction)], []),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };