/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Language = string;
export interface MatchAction { 'user' : Principal, 'timestamp' : bigint }
export interface Message {
  'content' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : bigint,
}
export interface ShortProfile {
  'age' : bigint,
  'bio' : string,
  'fullName' : string,
  'nativeLanguages' : Array<Language>,
  'targetLanguages' : Array<Language>,
  'currentStatus' : Status,
}
export type Status = { 'active' : null } |
  { 'offline' : null };
export interface UserProfile {
  'age' : bigint,
  'bio' : string,
  'interests' : Array<string>,
  'fullName' : string,
  'sentMatchRequests' : Array<Principal>,
  'matches' : Array<Principal>,
  'nativeLanguages' : Array<Language>,
  'targetLanguages' : Array<Language>,
  'lastActive' : bigint,
  'currentStatus' : Status,
  'lastMessageCheck' : bigint,
  'receivedMatchRequests' : Array<Principal>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUserProfile' : ActorMethod<[ShortProfile], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentActiveParticipants' : ActorMethod<[], Array<[Principal, Status]>>,
  'getCurrentUserProfile' : ActorMethod<[], UserProfile>,
  'getMatches' : ActorMethod<[], Array<MatchAction>>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeUser' : ActorMethod<[Principal], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];